syntax = "proto2";

package app;

message InitParam {
    repeated string coco_names = 1;
    optional string model_path = 2;
    optional int32 image_reader_width = 3;
    optional int32 image_reader_height = 4;
    optional int32 model_frame_width = 5;
    optional int32 model_frame_height = 6;
}

message CameraInfo {
    optional string id = 1;
    optional uint32 sensor_rotation = 2;
    optional bool is_front = 3;
    repeated Size cameraSizes = 4;
    repeated Range fps_ranges = 5;
}

message Camera {
  optional string id = 1;
  optional bool is_front = 2;
  optional uint32 sensor = 3;
  optional Size size = 4;
}

message Range {
    optional uint32 lower = 1;
    optional uint32 upper = 2;
}

message Size {
    optional uint32 width = 1;
    optional uint32 height = 2;
}

message EventWrapper {
    oneof msg {
        Detection detection = 1;
        FrameSaved frame_saved = 2;
    }
}

message Detection {
    repeated DetectionItem item = 1;
    optional int32 frame_count = 4;
    optional int64 timestamp_ns = 5;
}

message DetectionItem {
    optional Rect detection = 1;
    optional int32 class_id = 2;
    optional float confidence = 3;
}

message FrameSaved {
    optional string path = 1;
}

message Rect {
    optional double x = 1;
    optional double y = 2;
    optional double width = 3;
    optional double height = 4;
}